### PR TITLE
Updating to support Akka 1.3.1

### PR DESCRIPTION
**Pull request by joshgarnett**
This has been updated to use the latest Akka 1.3.1 packages.  It has not been updated to support .net core.

### CODE REVIEW

**Comment by joshgarnett** [comment]
Do not merge this PR.  I'm waiting on the some PRs to be merged and release in the Akka project first.

**Comment by alexvaluyskiy** [comment]
@joshgarnett If you add some commits to this PR - AppVeyor should take them and run tests

**Comment by joshgarnett** [comment]
Added the migration steps, I made sure to call out users should be testing before running in production as I have no easy way to test a large production set of data.

**Comment by alexvaluyskiy** [comment]
@joshgarnett We are looking for maintainers for AkkaNetContrib plugins. If you use this plugin in your projects, you could become a maintainer of this package. What do you think?

**Comment by joshgarnett** [comment]
@alexvaluyskiy let me follow up with my company first.  I also plan on writing a separate MySQL plugin that supports sharding and numeric persistence ids.  I don't think it would make sense to do that work in the context of this project.

**Pull request merged**
